
#   测试环境：java -jar file-server.jar --spring.profiles.active=test
#   开发环境：java -jar flie-server.jar --spring.profiles.active=dev
#   生产环境：java -jar file-server.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  application:
    name: file-server
  # JPA
  jpa:
    open-in-view: true
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  servlet:
      multipart:
        enabled: true
        max-file-size: 25MB      # 设置上传文件最大大小
        max-request-size: 100MB  # 设置上传文件总大小




# 使用 swagger 如果字段的类型为Long或是int类型 后台会报java.lang.NumberFormatException: For input string: ""；忽略这个错误
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error